name: CI Next.js

on:
  push:
    branches:
      - master   # exécute le pipeline à chaque push sur main
  pull_request:  # et aussi sur chaque PR

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Build l’application
      - name: Build Next.js
        run: npm run build

      # Étape 5 : Export en statique
      - name: Export static site
        run: npm run export

      # Étape 6 : Sauvegarder les fichiers générés en artifact
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: out/
